# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7be495c0843726fa469ffe86af024f0369505e8cfab7df4a32c0e6816c5b2c10102184dc5c4aad696f8422223599a42aeb5e461c0d3971075bb12e7b479af19

test:
  secret_key_base: c3c8544ba14a4c06999be3bf827b6661f7c342cc7ea00d469f6f843e0c437c47a093c417e6847933d9a9e1e3943c4e366ea40eefbf8f8506dce9c1eb2ee02949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
